spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTS}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
server:
  port: ${SERVER_PORT}

app:
  nginx:
    port: ${NGINX_PORT}
  queue:
    name: ${RABBIT_QUEUE}
  external:
    schedule:
      address: "http://${SCHEDULE_SERVICE_HOSTS}"
    user:
      address: "http://${USER_SERVICE_HOSTS}"

